package com.codaconsultancy.sandbox.euler;

public class EvenFibonacci {

//    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//    By starting with 1 and 2, the first 10 terms will be:
//            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    private static final int MAX = 4000000;

    public static void main(String[] args) {
        int firstNumber = 0;
        int secondNumber = 1;
        int sum;
        int total = 0;

        while (firstNumber < MAX && secondNumber < MAX) {

            sum = firstNumber + secondNumber;

            if (isEven(sum)) {
                total += sum;
            }

            firstNumber = secondNumber;
            secondNumber = sum;
        }

        System.out.println("Sum of even-valued terms = " + total);
    }

    private static boolean isEven(int number) {
        return number % 2 == 0;
    }

}
